# Generated by Django 5.2.5 on 2025-08-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
