# Generated by Django 5.2.5 on 2025-08-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lap', '0004_alter_categorydb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catname', models.CharField(blank=True, max_length=20, null=True)),
                ('Pname', models.CharField(blank=True, max_length=20, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Desc', models.CharField(blank=True, max_length=50, null=True)),
                ('Pimage1', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('Pimage2', models.ImageField(blank=True, null=True, upload_to='product/')),
            ],
        ),
    ]
