# Generated by Django 5.2.5 on 2025-08-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lap', '0002_alter_categorydb_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydb',
            old_name='img',
            new_name='image',
        ),
    ]
