# Generated by Django 5.2.5 on 2025-08-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lap', '0003_rename_img_categorydb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
