# Generated by Django 5.2.5 on 2025-10-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontLap', '0002_userregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='Name',
            new_name='UserName',
        ),
        migrations.AlterField(
            model_name='userregister',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
