# Generated by Django 5.2.5 on 2025-10-25 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontLap', '0004_cartdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Product', models.CharField(blank=True, max_length=50, null=True)),
                ('Qty', models.IntegerField(default=1)),
                ('PurchaseDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('CARD', 'Credit/Debit Card'), ('UPI', 'UPI')], default='COD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddressDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Pin', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
